In [140]:
import pandas as pd

In [141]:
ls

data_cleaning.ipynb                  data_professional_survey_clean.csv
data_professional_survey.csv         data_professional_survey_clean.xlsx
data_professional_survey.xlsx

In [142]:
df = pd.read_csv('data_professional_survey.csv', index_col=None)  
df.columns

Index(['Unique ID', 'Email', 'Date Taken (America/New_York)',
       'Time Taken (America/New_York)', 'Time Spent',
       'Q1 - Which Title Best Fits your Current Role?',
       'Q2 - Did you switch careers into Data?',
       'Q3 - Current Yearly Salary (in USD)',
       'Q4 - What Industry do you work in?',
       'Q5 - Favorite Programming Language',
       'Q6 - How Happy are you in your Current Position with the following? (Salary)',
       'Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)',
       'Q6 - How Happy are you in your Current Position with the following? (Coworkers)',
       'Q6 - How Happy are you in your Current Position with the following? (Management)',
       'Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)',
       'Q6 - How Happy are you in your Current Position with the following? (Learning New Things)',
       'Q7 - How difficult was it for you to break into Data?',
       'Q8 - If you were to look for a new job today, what would be the most important thing to you?',
       'Q9 - Male/Female?', 'Q10 - Current Age',
       'Q11 - Which Country do you live in?',
       'Q12 - Highest Level of Education', 'Q13 - Ethnicity'],
      dtype='object')

In [143]:
df.head(5)

,Unique ID,Email,Date Taken (America/New_York),Time Taken (America/New_York),Time Spent,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,anonymous,6/10/2022,8:38,0:00:44,Data Analyst,Yes,106k-125k,Healthcare,Python,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,anonymous,6/10/2022,8:40,0:01:30,Data Analyst,No,41k-65k,Finance,R,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,anonymous,6/10/2022,8:42,0:02:18,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,NaN,Black or African American
3,62a33c8624a26260273822f9,anonymous,6/10/2022,8:43,0:02:10,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
4,62a33c91f3072dd892621e03,anonymous,6/10/2022,8:44,0:01:51,Data Analyst,Yes,41k-65k,Healthcare,R,...,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American

In [144]:
df = df.drop(columns=['Email'])
df.head(4)

,Unique ID,Date Taken (America/New_York),Time Taken (America/New_York),Time Spent,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,Q6 - How Happy are you in your Current Position with the following? (Salary),...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,6/10/2022,8:38,0:00:44,Data Analyst,Yes,106k-125k,Healthcare,Python,9.0,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,6/10/2022,8:40,0:01:30,Data Analyst,No,41k-65k,Finance,R,1.0,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,6/10/2022,8:42,0:02:18,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,0.0,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,NaN,Black or African American
3,62a33c8624a26260273822f9,6/10/2022,8:43,0:02:10,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,10.0,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian

In [145]:
cols = ['Q1 - Which Title Best Fits your Current Role?', 
        'Q4 - What Industry do you work in?', 
        'Q5 - Favorite Programming Language',
        'Q8 - If you were to look for a new job today, what would be the most important thing to you?',
       'Q11 - Which Country do you live in?']

for col in cols:
    for k, item in enumerate(df[col]):
        if 'Other' in item:
            df[col][k] = 'Others'

/var/folders/_z/3pmrv3fj7l79p67vvbgb2cdh0000gn/T/ipykernel_83909/3172895071.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col][k] = 'Others'

In [146]:
df.head(5)

,Unique ID,Date Taken (America/New_York),Time Taken (America/New_York),Time Spent,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,Q6 - How Happy are you in your Current Position with the following? (Salary),...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,6/10/2022,8:38,0:00:44,Data Analyst,Yes,106k-125k,Healthcare,Python,9.0,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,6/10/2022,8:40,0:01:30,Data Analyst,No,41k-65k,Finance,R,1.0,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,6/10/2022,8:42,0:02:18,Data Engineer,No,0-40k,Others,Python,0.0,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Others,NaN,Black or African American
3,62a33c8624a26260273822f9,6/10/2022,8:43,0:02:10,Others,Yes,150k-225k,Finance,R,10.0,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
4,62a33c91f3072dd892621e03,6/10/2022,8:44,0:01:51,Data Analyst,Yes,41k-65k,Healthcare,R,1.0,...,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American

Convert Q3 - Current Yearly Salary (in USD) to average salary

In [147]:
length = len(df['Q3 - Current Yearly Salary (in USD)'])
for i in range(0, length):
    salary = df['Q3 - Current Yearly Salary (in USD)'][i].split('-')
    #print(len(salary), i)
    for k in range(0,len(salary)):
        if salary[k] == '0':
            salary[k] = int(salary[k])
        else: 
            if salary[k][-1] == 'k':
                salary[k] = int(salary[k][:-1])
            else:
                salary[k] = int(salary[k][:-2])
    salary_ave = sum(salary)/len(salary)        
    df['Q3 - Current Yearly Salary (in USD)'][i] = salary_ave

/var/folders/_z/3pmrv3fj7l79p67vvbgb2cdh0000gn/T/ipykernel_83909/46282458.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Q3 - Current Yearly Salary (in USD)'][i] = salary_ave

In [148]:
df.rename({'Q3 - Current Yearly Salary (in USD)': 'Q3 - Average Salary (in USD)'}, axis=1, inplace=True)

In [149]:
df.head(5)

,Unique ID,Date Taken (America/New_York),Time Taken (America/New_York),Time Spent,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Average Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,Q6 - How Happy are you in your Current Position with the following? (Salary),...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,6/10/2022,8:38,0:00:44,Data Analyst,Yes,115.5,Healthcare,Python,9.0,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,6/10/2022,8:40,0:01:30,Data Analyst,No,53,Finance,R,1.0,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,6/10/2022,8:42,0:02:18,Data Engineer,No,20,Others,Python,0.0,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Others,NaN,Black or African American
3,62a33c8624a26260273822f9,6/10/2022,8:43,0:02:10,Others,Yes,187.5,Finance,R,10.0,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
4,62a33c91f3072dd892621e03,6/10/2022,8:44,0:01:51,Data Analyst,Yes,53,Healthcare,R,1.0,...,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American

In [150]:
df.to_csv('data_professional_survey_clean.csv')

In [151]:
df2 = pd.read_csv('data_professional_survey_clean.csv', index_col=None)  
df2.head(5)

,Unnamed: 0,Unique ID,Date Taken (America/New_York),Time Taken (America/New_York),Time Spent,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Average Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,0,62a33b3db4da29969c62df3d,6/10/2022,8:38,0:00:44,Data Analyst,Yes,115.5,Healthcare,Python,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,1,62a33ba1bae91e4b8b82e35c,6/10/2022,8:40,0:01:30,Data Analyst,No,53.0,Finance,R,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,2,62a33c2cbc6861bf3176bec1,6/10/2022,8:42,0:02:18,Data Engineer,No,20.0,Others,Python,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Others,NaN,Black or African American
3,3,62a33c8624a26260273822f9,6/10/2022,8:43,0:02:10,Others,Yes,187.5,Finance,R,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
4,4,62a33c91f3072dd892621e03,6/10/2022,8:44,0:01:51,Data Analyst,Yes,53.0,Healthcare,R,...,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American